apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: crontabs.training.lfs458.com
spec:
  scope: Cluster #could also be namespace
  group: training.lfs458.com
  version: v1
  names:
    kind: CronTab
    plural: crontabs
    singular: crontab 
    shortNames: 
    - ct