apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: sleepy-cron
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          activeDeadlineSeconds: 10 #job and pod ends after 10 seconds
          containers:
          - name: resting
            image: busybox
            command: ["bin/sleep"]
            args: ["5"]
          restartPolicy: Never