apiVersion: v1
kind: LimitRange #created and assigned to namespace.
metadata:
  name: low-resource-usage
spec:
  limits:
  - default: 
      cpu: 1
      memory: 500Mi

    defaultRequest:
      cpu: 0.5
      memory: 100Mi
    type: Container