apiVersion: v1
kind: Pod
metadata:
  name: shell-demo
  labels:
    app: nginx
spec:
  containers:
  - name: shell-demo-container
    image: nginx
    ports:
      - containerPort: 80

    envFrom:
      - configMapRef:
          name: colors