apiVersion: certificates.k8s.io/v1beta1 #from 1.19+ the apiversion will be certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: akshay
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBNQTBHQTFVRUF3d0dZV3R6YUdGNU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQXhZRkcwNGh3QTVWb1h2TWI0UFV5WnBVYjAyTkRQc293WVBhVlVaVGlrQWtjCnZxTm0zdSsrSnJsRWJsSEc1VUtRb0dqRUprSlJ1bzVwR0VOYXc0dHpJbDI0T1FTeUxDMW00N1FYRHRuWk5Ld0wKVW1ZU1Y4WDVBZ1p1am80aVpWK3VMajE3Y3dvdkZZWjZWYTlpd1N0SWQ3clNSbU1iblZBU1BnMERocmY1NHpSawp3M3o1Y0RrdFE3dEVjM2UzMlpRYUljQkVNNzYwbm9oMXpuenJLS0dKaVVUT2VXT2kvRmkvWjBOWHlpR2hsM0NBCnhDU2IxVllmUUNRQTRzWEtYSWpFUzF5QXZjcjM1MXZoMUhUL09LNUlvNW5jUEkydkhXQzUrc1lPWERCSEtGNy8KdlE3NWgyeHZ6bmt2QXdmV2RxRUJ1Yk9RUUVEdzZzQ1dscjhNOGZZU3d3SURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBS0tCU2k4aFd1S0FEOWxyb05iK3FDWnJTaVJ1ZHFncU9kZjZUTEt4VHJsQ1YybFVFeU5DCkhMampzY2Y3RWl3Z24vVEV5ckFWT3ZOejBweUJlL3dSZU9TSm9ROUU4OUo4UTRmdTlvUk5XbVJZNW5TRHowcU4KWWsxWjIrTkZzUUNLZGZmNWc0cDJoYm85VjB3cFJsUnRKcmNjK1pRV1VkT25VNElqTG1XQmNyK004NHhiaGgzcQo3RlZUcFJiWWhOcVpPOWJrVEY0UGpVWC9udVJnWnl6MklseVY3SWJFMXJ6ZmdlaEhwUUNaUVJJS25RQTQweEN2ClVKclBYQmp6SmE3Y05DZHJIeUE3NVNvQk1vZFlXUlJNY3hCdVNRbG9JZk80MUhJTTMvNEI1eWRjUWtnYml0UlYKL2NwdXVLSFQ4QjMrQWdvZnRaZG91Zkp4VVh5d0xuejBDbTA9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  usages:
  - digital signature
  - key encipherment
  - server auth
  signerName: kubernetes.io/kube-apiserver-client