apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-test
  labels:
      name: ingress-test
spec:
  rules:
  - host: www.example.com
    http:
      paths:
      - backend:
            serviceName: secondapp
            servicePort: 80
        path: /
