# create 2 secret beforehand.
#  kubectl create secret generic sec-a1 --from-literal=key1=supersecret
#  kubectl create secret generic sec-a2 --from-file=/etc/hosts
# kubectl create serviceaccount secret-manager

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secret-manager
  name: secret-manager
spec:
  containers:
  - image: 80.0.16.3/test123/nginx:1.19
    name: secret-manager
    resources: {}
    volumeMounts:
    - name: secret-mount # secret mounted as volume
      mountPath: /etc/sec-a2
      readOnly: true
    env:
    - name: SEC_A1  # secret mounted as env variable
      valueFrom:
        secretKeyRef:
          name: sec-a1
          key: key1
  serviceAccountName: secret-manager
  volumes:
  - name: secret-mount
    secret:
      secretName: sec-a2
  dnsPolicy: ClusterFirst
  restartPolicy: Always