apiVersion: v1 #Version of the API, kube-api server instructs where to assign data
clusters:
- cluster: #Name of the cluster as well as where to send API Calls, ca is passed to authenticate curl request. 
    certificate-authority-data: LS0tLS1CRUdF.....
    server: https://10.128.0.3:6443 
    name: kubernetes 
contexts:
- context: #easy access to multiple clusters. possibly various users
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
current-context: kubernetes-admin@kubernetes #The current context kubectl command tries authenticate with
kind: Config #What kind of object this is config, can also be created using kubectl config set-credentials
preferences: {}
users: #Defines the user ,client certificate and client username/password. 
- name: kubernetes-admin
  user:
    client-certificate-data: LS0tLS1CRUdJTib.....
    client-key-data: LS0tLS1CRUdJTi....