# Create a new pod called nginx with the image nginx:alpine. The Pod should make use of the PVC 
#local-pvc and mount the volume at the path /var/www/html

apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: web
spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
      - containerPort: 80
    volumeMounts:
      - mountPath: /var/www/html
        name: pvc

  volumes:
    - name: pvc 
      persistentVolumeClaim:
        claimName: local-pvc
