apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_Host: c3FsMDE=
  DB_User: cm9vdA==
  DB_Password: cGFzc3dvcmQxMjM=


---

apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  labels:
    name: myapp
spec:
  containers:
  - name: webapp-container
    image: kodekloud/simple-webapp-mysql
    envFrom:
      - secretRef:
          name: db-secret

